CF.Music[CF.MusicTypes.SHIP_CALM] = "Void Wanderers Ship Calm"
CF.Music[CF.MusicTypes.SHIP_INTENSE] = "Void Wanderers Ship Intense"
CF.Music[CF.MusicTypes.MISSION_CALM] = "Void Wanderers Mission Calm"
CF.Music[CF.MusicTypes.MISSION_INTENSE] = "Void Wanderers Mission Intense"
CF.Music[CF.MusicTypes.VICTORY] = "Void Wanderers Victory"
CF.Music[CF.MusicTypes.DEFEAT] = "Void Wanderers Defeat"
CF.Music[CF.MusicTypes.COMMERCE] = "Void Wanderers Commerce"