-- items that are generated by quantum skills

local id = "Anti Personnel Mine"
CF["QuantumItems"][#CF["QuantumItems"] + 1] = id
CF["QuantumItmPresets"][id] = "Anti Personnel Mine"
CF["QuantumItmModules"][id] = "Base.rte"
CF["QuantumItmClasses"][id] = "TDExplosive"
CF["QuantumItmPrices"][id] = 20

local id = "Remote Explosive"
CF["QuantumItems"][#CF["QuantumItems"] + 1] = id
CF["QuantumItmPresets"][id] = "Remote Explosive"
CF["QuantumItmModules"][id] = "Base.rte"
CF["QuantumItmClasses"][id] = "TDExplosive"
CF["QuantumItmPrices"][id] = 25

local id = "Frag Grenade"
CF["QuantumItems"][#CF["QuantumItems"] + 1] = id
CF["QuantumItmPresets"][id] = "Frag Grenade"
CF["QuantumItmModules"][id] = "Coalition.rte"
CF["QuantumItmClasses"][id] = "TDExplosive"
CF["QuantumItmPrices"][id] = 10

local id = "Cluster Grenade"
CF["QuantumItems"][#CF["QuantumItems"] + 1] = id
CF["QuantumItmPresets"][id] = "Cluster Grenade"
CF["QuantumItmModules"][id] = "Coalition.rte"
CF["QuantumItmClasses"][id] = "TDExplosive"
CF["QuantumItmPrices"][id] = 20

local id = "Medikit"
CF["QuantumItems"][#CF["QuantumItems"] + 1] = id
CF["QuantumItmPresets"][id] = "Medikit"
CF["QuantumItmModules"][id] = "Base.rte"
CF["QuantumItmClasses"][id] = "HDFirearm"
CF["QuantumItmPrices"][id] = 20
