-- items that are generated by quantum skills

local id = "Anti Personnel Mine";
CF.QuantumItems[#CF.QuantumItems + 1] = id;
CF.QuantumItmClasses[id] = "TDExplosive";
CF.QuantumItmPresets[id] = "Anti Personnel Mine";
CF.QuantumItmModules[id] = "Base.rte";
CF.QuantumItmPrices[id] = 8;

local id = "Remote Explosive";
CF.QuantumItems[#CF.QuantumItems + 1] = id;
CF.QuantumItmClasses[id] = "TDExplosive";
CF.QuantumItmPresets[id] = "Remote Explosive";
CF.QuantumItmModules[id] = "Base.rte";
CF.QuantumItmPrices[id] = 15;

local id = "Frag Grenade";
CF.QuantumItems[#CF.QuantumItems + 1] = id;
CF.QuantumItmClasses[id] = "TDExplosive";
CF.QuantumItmPresets[id] = "Frag Grenade";
CF.QuantumItmModules[id] = "Coalition.rte";
CF.QuantumItmPrices[id] = 5;

local id = "Cluster Grenade";
CF.QuantumItems[#CF.QuantumItems + 1] = id;
CF.QuantumItmClasses[id] = "TDExplosive";
CF.QuantumItmPresets[id] = "Cluster Grenade";
CF.QuantumItmModules[id] = "Coalition.rte";
CF.QuantumItmPrices[id] = 8;

local id = "Medikit";
CF.QuantumItems[#CF.QuantumItems + 1] = id;
CF.QuantumItmClasses[id] = "HDFirearm";
CF.QuantumItmPresets[id] = "Medikit";
CF.QuantumItmModules[id] = "Base.rte";
CF.QuantumItmPrices[id] = 20;

local id = "Prosthetic Leg";
CF.QuantumItems[#CF.QuantumItems + 1] = id;
CF.QuantumItmClasses[id] = "HeldDevice";
CF.QuantumItmPresets[id] = "Prosthetic Leg";
CF.QuantumItmModules[id] = "VoidWanderers.rte";
CF.QuantumItmPrices[id] = 60;

local id = "Prosthetic Arm";
CF.QuantumItems[#CF.QuantumItems + 1] = id;
CF.QuantumItmClasses[id] = "HeldDevice";
CF.QuantumItmPresets[id] = "Prosthetic Arm";
CF.QuantumItmModules[id] = "VoidWanderers.rte";
CF.QuantumItmPrices[id] = 70;

local id = "Replacement Head";
CF.QuantumItems[#CF.QuantumItems + 1] = id;
CF.QuantumItmClasses[id] = "HeldDevice";
CF.QuantumItmPresets[id] = "Replacement Head";
CF.QuantumItmModules[id] = "VoidWanderers.rte";
CF.QuantumItmPrices[id] = 150;
